#!/usr/bin/env python3

import hcl2
import sys
import os

def main():
    tfvars_file = 'terraform.tfvars'
    if not os.path.exists(tfvars_file):
        print(f"Error: {tfvars_file} not found")
        sys.exit(1)

    with open(tfvars_file, 'r') as f:
        tfvars = hcl2.load(f)

    cross_account_providers = tfvars.get('cross_account_providers', {})

    if not cross_account_providers:
        print("No cross_account_providers found in terraform.tfvars")
        return

    # Create or append to providers.tf
    providers_content = "# Additional providers for cross-account access\n# Generated by generate_providers.py\n\n"

    for account_name, account_config in cross_account_providers.items():
        role_arn = account_config.get('role_arn')
        account_id = account_config.get('account_id')
        
        if not role_arn:
            print(f"Warning: Missing role_arn for account '{account_name}', skipping")
            continue
            
        providers_content += f'''provider "aws" {{
  region = var.region
  assume_role {{
    role_arn = "{role_arn}"
  }}
  alias = "account_{account_name}"
}}

'''

    with open('providers.tf', 'w') as f:
        f.write(providers_content)

    print(f"Generated providers.tf with {len(cross_account_providers)} cross-account providers")

if __name__ == "__main__":
    main()